#################################################################
#                                                               #
#    Copyright (C) 2018-2024 Simon O'Meara : 			 #
#    simon.omeara@manchester.ac.uk              		 #
#                                                               #
#    All Rights Reserved.                                       #
#    This file is part of PyCHAM                                #
#                                                               #
#    PyCHAM is free software: you can redistribute it and/or modify it under              #
#    the terms of the GNU General Public License as published by the Free Software        #
#    Foundation, either version 3 of the License, or (at your option) any later           #
#    version.                                                                             #
#                                                                                        											 #
#    PyCHAM is distributed in the hope that it will be useful, but WITHOUT                #
#    ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS        #
#    FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more               #
#    details.                                                                             #
#                                                                                        											 #
#    You should have received a copy of the GNU General Public License along with         #
#    PyCHAM.  If not, see <http://www.gnu.org/licenses/>.                                 #
#                                                                                        											 #
###################################################################################
'''module for calculating accommodation coefficients,
 automatically generated by
 partit_var_prep'''

# code that expresses and performs the functions for accommodation 
# coefficients that are given by the user in the model variables file 
# and that are intended to be calculated real-time via the kimt_calc 
# module 

def accom_coeff_func(accom_coeff, Rp, self):

	# -------------------------------------------------------------- 
	# inputs:
	# accom_coeff - array containing accommodation coefficients for all 
	# components (rows) and size bins (columns) (including walls)
	# Rp - radii of size bins (m)
	# --------------------------------------------------------------- 

	import numpy as np
	# calculate accommodation coefficients 
	accom_coeff[:, 0:self.num_asb] = 1. 

	return(accom_coeff)
