'''module for calculating scattering phase function'''
# generated by nat_act_flux, with content provided by user 

# File Created at 2021-04-30 18:07:39.621725

import numpy as np 

def Pfunc(theta):
	
	# inputs -------------------
		theta - the downward scattering angle - equal to the solar zenith angle
	-------------------------------
	
(3./4.)*(1.+(np.cos(ThetaP))**2.)
	return(Pall)